apiVersion: v1
kind: Pod
metadata:
  name: pod-baleado
spec:
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
      env:
        - name: DB_PASSWORD
          value: "senha123"
